#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-2020, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

CFLAGS     =
FFLAGS     =
CPPFLAGS   =
FPPFLAGS   =
DIRS       = nlevp
LOCDIR     = src/nep/tutorials/
EXAMPLESC  = ex20.c ex21.c ex22.c ex27.c ex42.c
EXAMPLESF  = ex20f90.F90 ex22f90.F90 ex27f90.F90
MANSEC     = NEP

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
