#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-2020, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

#requirespackage 'PETSC_HAVE_CUDA'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCECU = sveccuda.cu
SOURCEF  =
SOURCEH  =
LIBBASE  = libslepcsys
DIRS     =
MANSEC   = BV
LOCDIR   = src/sys/classes/bv/impls/svec/sveccuda/

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common


