#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-2020, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = svec.c
SOURCEF  =
SOURCEH  = svec.h
LIBBASE  = libslepcsys
DIRS     = sveccuda
MANSEC   = BV
LOCDIR   = src/sys/classes/bv/impls/svec/

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common


