
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = epssolvef.c epsmonf.c epsdefaultf.c epsbasicf.c epssetupf.c epsviewf.c epsoptsf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepceps
LOCDIR   = src/eps/interface/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
