
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dsbasicf.c dsopsf.c dsprivf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcsys
LOCDIR   = src/sys/classes/ds/interface/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
