
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = svdviewf.c svdoptsf.c svdbasicf.c svdsetupf.c svdmonf.c svdsolvef.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcsvd
LOCDIR   = src/svd/interface/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
