#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-2020, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = bvbasic.c bvfunc.c bvops.c bvglobal.c bvblas.c bvlapack.c bvorthog.c bvbiorthog.c bvkrylov.c bvregis.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libslepcsys
DIRS     = cuda
MANSEC   = BV
LOCDIR   = src/sys/classes/bv/interface/

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common


