
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = interpolf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcnep
LOCDIR   = src/nep/impls/interpol/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
