
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pepbasicf.c pepsetupf.c pepdefaultf.c pepsolvef.c pepviewf.c pepoptsf.c pepmonf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcpep
LOCDIR   = src/pep/interface/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
