
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = stsolvef.c stfuncf.c stsetf.c stslesf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcsys
LOCDIR   = src/sys/classes/st/interface/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
