#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-2020, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = slepcinit.c slepcutil.c slepcsc.c dlregisslepc.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libslepcsys
MANSEC   = sys
LOCDIR   = src/sys/
DIRS     = f90-mod vec mat classes tests tutorials

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common

