#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-2020, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = slepc.h slepcsys.h slepcmath.h slepcversion.h slepcblaslapack.h \
           slepceps.h slepcpep.h slepcnep.h slepcsvd.h slepcmfn.h slepclme.h \
           slepcst.h slepcds.h slepcfn.h slepcrg.h slepcbv.h slepcvec.h \
           slepcblaslapack_mangle.h slepcmat.h slepcrgtypes.h slepcsc.h
LIBBASE  = libslepcsys
DIRS     = slepc/finclude slepc/private
LOCDIR   = include/
MANSEC   =

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
