
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = nepresolvf.c nepbasicf.c nepsetupf.c nepoptsf.c nepviewf.c nepsolvef.c nepdefaultf.c nepmonf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcnep
LOCDIR   = src/nep/interface/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
