
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = bvopsf.c bvorthogf.c bvkrylovf.c bvfuncf.c bvbasicf.c bvglobalf.c bvbiorthogf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcsys
LOCDIR   = src/sys/classes/bv/interface/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
