
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = gdf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepceps
LOCDIR   = src/eps/impls/davidson/gd/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
