
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = gklanczosf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcsvd
LOCDIR   = src/svd/impls/lanczos/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
