
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = ptoarf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcpep
LOCDIR   = src/pep/impls/krylov/toar/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
