
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = rqcgf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepceps
LOCDIR   = src/eps/impls/cg/rqcg/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
