
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = lmesetupf.c lmebasicf.c lmesolvef.c lmeoptsf.c lmemonf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepclme
LOCDIR   = src/lme/interface/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
