#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-2020, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

CFLAGS     =
FFLAGS     =
CPPFLAGS   =
FPPFLAGS   =
DIRS       = nlevp
LOCDIR     = src/pep/tutorials/
EXAMPLESC  = ex16.c ex17.c ex28.c ex38.c
EXAMPLESF  = ex16f90.F90
MANSEC     = PEP

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
