
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = rgpolygonf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcsys
LOCDIR   = src/sys/classes/rg/impls/polygon/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
