module vector_mod
  use vector_integer_mod
  use vector_real_mod
  use vector_complex_mod
  use vector_string_mod
  use vector_vector_integer_mod
  use vector_vector_real_mod
  use vector_array_1d_integer_mod
  use vector_array_1d_real_mod
  use vector_array_1d_complex_mod
end module
