#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-2020, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

ALL: lib

SOURCEH  = ../../include/slepc/private/mfnimpl.h ../../include/slepcmfn.h
DIRS     = interface impls tests tutorials f90-mod
LOCDIR   = src/mfn/
MANSEC   = MFN

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common


