#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-2020, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

CFLAGS     =
FFLAGS     =
CPPFLAGS   =
FPPFLAGS   =
LOCDIR     = src/nep/tests/
EXAMPLESC  = test1.c test2.c test3.c test4.c test5.c test6.c test7.c test8.c test9.c \
             test10.c test11.c test12.c test13.c test14.c test15.c
EXAMPLESF  = test2f.F
MANSEC     = NEP
TESTS      = test1 test2 test2f test3 test4 test5 test6 test7 test8 test9 test10 test11 \
             test12 test13 test14 test15

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
