#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-2020, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pepmon.c pepbasic.c pepview.c pepdefault.c pepregis.c pepopts.c pepsetup.c pepsolve.c peprefine.c dlregispep.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libslepcpep
DIRS     =
MANSEC   = PEP
LOCDIR   = src/pep/interface/

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common


