#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-2020, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

ALL: lib

LIBBASE  = libslepceps
DIRS     = power subspace krylov davidson cg ciss lyapii lapack external
LOCDIR   = src/eps/impls/
MANSEC   = EPS

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common


