
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#  SLEPc - Scalable Library for Eigenvalue Problem Computations
#  Copyright (c) 2002-2020, Universitat Politecnica de Valencia, Spain
#
#  This file is part of SLEPc.
#  SLEPc is distributed under a 2-clause BSD license (see LICENSE).
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#requiresdefine   'PETSC_HAVE_FORTRAN'

CFLAGS     =
FFLAGS     =
SOURCEC    =
SOURCEF90  = slepcmfnmod.F90
SOURCEH    = slepcmfn.h slepcmfn.h90
LIBBASE    = libslepcmfn
MANSEC     = MFN
LOCDIR     = src/mfn/f90-mod/
CLEANFILES = *.mod

include ${SLEPC_DIR}/lib/slepc/conf/slepc_common

